#!/usr/bin/env python3
"""Generate the Next.js v2 match dataset from the static-site source of truth."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
APP_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from match_data import MATCHES  # noqa: E402


def pair(value: list[Any] | tuple[Any, ...]) -> dict[str, Any]:
    return {"value": value[0], "label": value[1]}


def normalize_match(match: dict[str, Any]) -> dict[str, Any]:
    return {
        "slug": match["slug"],
        "home": match["home"],
        "away": match["away"],
        "homeCode": match["home_code"],
        "awayCode": match["away_code"],
        "homeEmoji": match["home_emoji"],
        "awayEmoji": match["away_emoji"],
        "group": match["group"],
        "matchday": match["matchday"],
        "dateStr": match["date_str"],
        "dateShort": match["date_short"],
        "timeStr": match["time_str"],
        "venue": match["venue"],
        "venueShort": match["venue_short"],
        "venueName": match["venue_name"],
        "venueAddr": match["venue_addr"],
        "jsonDt": match["json_dt"],
        "homeMl": match["home_ml"],
        "drawMl": match["draw_ml"],
        "awayMl": match["away_ml"],
        "ouLine": match["ou_line"],
        "ouOver": match["ou_over"],
        "ouUnder": match["ou_under"],
        "homeProb": match["home_prob"],
        "drawProb": match["draw_prob"],
        "awayProb": match["away_prob"],
        "favName": match["fav_name"],
        "favMl": match["fav_ml"],
        "predResult": match["pred_result"],
        "homeRank": match["home_rank"],
        "awayRank": match["away_rank"],
        "photo": match["photo"],
        "chips": [{"text": text, "positive": positive} for text, positive in match["chips"]],
        "homeH3": match["home_h3"],
        "homeP1": match["home_p1"],
        "homeP2": match["home_p2"],
        "awayH3": match["away_h3"],
        "awayP1": match["away_p1"],
        "awayP2": match["away_p2"],
        "h2h": match["h2h"],
        "homeStats": [pair(row) for row in match["home_stats"]],
        "awayStats": [pair(row) for row in match["away_stats"]],
        "statRows": [
            {
                "homeValue": home_value,
                "label": label,
                "homePercent": home_percent,
                "awayValue": away_value,
            }
            for home_value, label, home_percent, away_value in match["stat_rows"]
        ],
        "picks": [
            {"name": name, "detail": detail, "tag": tag, "odds": odds}
            for name, detail, tag, odds in match["picks"]
        ],
        "fantasy": [
            {
                "flag": flag,
                "playerName": player_name,
                "meta": meta,
                "projectedPoints": projected_points,
                "ownership": ownership,
                "highRisk": high_risk,
            }
            for flag, player_name, meta, projected_points, ownership, high_risk in match["fantasy"]
        ],
        "trending": [{"text": text, "badge": badge} for text, badge in match["trending"]],
        "upNext": [
            {"match": text, "timeLabel": time_label, "href": href}
            for text, time_label, href in match["up_next"]
        ],
    }


def main() -> None:
    matches = [normalize_match(match) for match in MATCHES]
    payload = json.dumps(matches, ensure_ascii=False, indent=2)
    output = f'''/* AUTO-GENERATED by scripts/generate_matches_ts.py.
   Source of truth: ../../match_data.py. Do not edit this file by hand. */

export interface MatchChip {{
  text: string;
  positive: boolean;
}}

export interface MatchStatPair {{
  value: string;
  label: string;
}}

export interface MatchStatRow {{
  homeValue: string;
  label: string;
  homePercent: number;
  awayValue: string;
}}

export interface MatchPick {{
  name: string;
  detail: string;
  tag: string;
  odds: string;
}}

export interface MatchFantasyPick {{
  flag: string;
  playerName: string;
  meta: string;
  projectedPoints: string;
  ownership: string;
  highRisk: boolean;
}}

export interface MatchTrend {{
  text: string;
  badge: string;
}}

export interface MatchNextLink {{
  match: string;
  timeLabel: string;
  href: string;
}}

export interface Match {{
  slug: string;
  home: string;
  away: string;
  homeCode: string;
  awayCode: string;
  homeEmoji: string;
  awayEmoji: string;
  group: string;
  matchday: number;
  dateStr: string;
  dateShort: string;
  timeStr: string;
  venue: string;
  venueShort: string;
  venueName: string;
  venueAddr: string;
  jsonDt: string;
  homeMl: string;
  drawMl: string;
  awayMl: string;
  ouLine: string;
  ouOver: string;
  ouUnder: string;
  homeProb: number;
  drawProb: number;
  awayProb: number;
  favName: string;
  favMl: string;
  predResult: string;
  homeRank: string;
  awayRank: string;
  photo: string;
  chips: MatchChip[];
  homeH3: string;
  homeP1: string;
  homeP2: string;
  awayH3: string;
  awayP1: string;
  awayP2: string;
  h2h: string;
  homeStats: MatchStatPair[];
  awayStats: MatchStatPair[];
  statRows: MatchStatRow[];
  picks: MatchPick[];
  fantasy: MatchFantasyPick[];
  trending: MatchTrend[];
  upNext: MatchNextLink[];
}}

export const MATCHES: Match[] = {payload};

export function toTeamSlug(value: string): string {{
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}}

const MATCH_BY_SLUG = new Map(MATCHES.map((match) => [match.slug, match]));

export function getMatchBySlug(slug: string): Match | undefined {{
  return MATCH_BY_SLUG.get(slug);
}}

export function getMatchesByTeam(teamSlugOrName: string): Match[] {{
  const normalized = toTeamSlug(teamSlugOrName.replace(/-guide$/, ""));
  return MATCHES.filter((match) => {{
    return (
      toTeamSlug(match.home) === normalized ||
      toTeamSlug(match.away) === normalized ||
      match.homeCode.toLowerCase() === normalized ||
      match.awayCode.toLowerCase() === normalized
    );
  }});
}}

export function getMatchesByGroup(group: string): Match[] {{
  const normalized = group.replace(/^group-/i, "").toUpperCase();
  return MATCHES.filter((match) => match.group.toUpperCase() === normalized);
}}

export function getTodaysMatches(
  date = new Date(),
  timeZone = "America/New_York"
): Match[] {{
  const formatter = new Intl.DateTimeFormat("en-CA", {{
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }});
  const todayKey = formatter.format(date);
  return MATCHES.filter((match) => formatter.format(new Date(match.jsonDt)) === todayKey);
}}
'''
    (APP_ROOT / "data" / "matches.ts").write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
