import type { Match } from "@/data/matches";
import { AffiliateOddsSlot, OddsDisclaimer } from "./OddsCompliance";
import {
  BottomArticleSignup,
  FantasyToolCta,
  MidArticleSignup,
  StickyLiveScoresLink,
} from "./ConversionCtas";

function impliedProbability(odds: string): string {
  const value = Number(odds.replace("+", ""));
  if (Number.isNaN(value)) return "N/A";
  const probability = value < 0 ? Math.abs(value) / (Math.abs(value) + 100) : 100 / (value + 100);
  return `${Math.round(probability * 100)}%`;
}

export function MatchHero({ match }: { match: Match }) {
  return (
    <section className="wc-hero match-page-hero">
      <div className="match-page-meta">
        Group {match.group} · Matchday {match.matchday} · {match.venue}
      </div>
      <h1>
        {match.home} vs {match.away}: Prediction, Odds, Fantasy Picks
      </h1>
      <p>
        {match.favName} are priced at {match.favMl}, which implies {impliedProbability(match.favMl)}.
        PitchIQ&rsquo;s AI read gives them {Math.max(match.homeProb, match.awayProb)}%.
      </p>
      <div className="match-scoreline">
        <div>
          <span>{match.homeEmoji}</span>
          <strong>{match.home}</strong>
          <em>{match.homeMl}</em>
        </div>
        <div className="match-vs">vs</div>
        <div>
          <span>{match.awayEmoji}</span>
          <strong>{match.away}</strong>
          <em>{match.awayMl}</em>
        </div>
      </div>
      <div className="ai-content-badge">AI Pick</div>
    </section>
  );
}

// LEGAL-REVIEW-REQUIRED
export function MatchOddsSection({ match }: { match: Match }) {
  const rows = [
    { label: `${match.home} win`, odds: match.homeMl, implied: impliedProbability(match.homeMl) },
    { label: "Draw", odds: match.drawMl, implied: impliedProbability(match.drawMl) },
    { label: `${match.away} win`, odds: match.awayMl, implied: impliedProbability(match.awayMl) },
    { label: `Over ${match.ouLine}`, odds: match.ouOver, implied: impliedProbability(match.ouOver) },
    { label: `Under ${match.ouLine}`, odds: match.ouUnder, implied: impliedProbability(match.ouUnder) },
  ];

  return (
    <section className="content-card odds-section">
      <div className="section-heading">
        <h2>Odds and Market Read</h2>
        <span className="ai-content-badge">AI Pick</span>
      </div>
      <div className="odds-table">
        {rows.map((row) => (
          <div className="odds-row" key={row.label}>
            <span>{row.label}</span>
            <strong>{row.odds}</strong>
            <em>{row.implied} implied</em>
          </div>
        ))}
      </div>
      <p>
        {match.favName} are the market side. The model&rsquo;s job is simple: compare that line to the
        win probability and skip prices that are already gone.
      </p>
      <AffiliateOddsSlot />
      <OddsDisclaimer />
    </section>
  );
}

export function MatchAnalysisSection({ match }: { match: Match }) {
  return (
    <section className="content-card">
      <div className="section-heading">
        <h2>Match Analysis</h2>
        <span className="ai-content-badge">AI Pick</span>
      </div>
      <div className="analysis-grid">
        <div>
          <h3>{match.home}: {match.homeH3}</h3>
          <p>{match.homeP1}</p>
          <p>{match.homeP2}</p>
        </div>
        <div>
          <h3>{match.away}: {match.awayH3}</h3>
          <p>{match.awayP1}</p>
          <p>{match.awayP2}</p>
        </div>
      </div>
      <div className="quick-stat-grid">
        {match.statRows.map((stat) => (
          <div key={stat.label}>
            <strong>{stat.homeValue}</strong>
            <span>{stat.label}</span>
            <em>{stat.awayValue}</em>
          </div>
        ))}
      </div>
      <p className="content-muted">{match.h2h}</p>
    </section>
  );
}

export function MatchPicksSection({ match }: { match: Match }) {
  return (
    <section className="content-card">
      <div className="section-heading">
        <h2>PitchIQ Picks</h2>
        <span className="ai-content-badge">AI Pick</span>
      </div>
      <div className="pick-list">
        {match.picks.map((pick) => (
          <div className="pick-list-row" key={pick.name}>
            <div>
              <strong>{pick.name}</strong>
              <span>{pick.detail}</span>
            </div>
            <em>{pick.tag}</em>
            <b>{pick.odds}</b>
          </div>
        ))}
      </div>
    </section>
  );
}

export function MatchFantasySection({ match }: { match: Match }) {
  return (
    <section className="content-card">
      <div className="section-heading">
        <h2>Top Fantasy Picks</h2>
        <span className="ai-content-badge">Generated by AI</span>
      </div>
      <div className="fantasy-mini-grid">
        {match.fantasy.slice(0, 5).map((player) => (
          <div className="fantasy-mini-card" key={player.playerName}>
            <div className="fantasy-mini-top">
              <span>{player.flag}</span>
              <strong>{player.playerName}</strong>
            </div>
            <p>{player.meta}</p>
            <div>
              <b>{player.projectedPoints}</b>
              <em>{player.ownership}</em>
            </div>
          </div>
        ))}
      </div>
      <FantasyToolCta />
    </section>
  );
}

export function MatchHub({ match }: { match: Match }) {
  return (
    <main className="content-page">
      <div className="content-wrap">
        <StickyLiveScoresLink />
        <MatchHero match={match} />
        <MatchAnalysisSection match={match} />
        <MidArticleSignup />
        <MatchOddsSection match={match} />
        <MatchPicksSection match={match} />
        <MatchFantasySection match={match} />
        <BottomArticleSignup />
      </div>
    </main>
  );
}
