import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/content/JsonLd";
import {
  BottomArticleSignup,
  FantasyToolCta,
  MidArticleSignup,
  StickyLiveScoresLink,
} from "@/components/content/ConversionCtas";
import { TEAM_GUIDES, getTeamGuideBySlug, getTeamGuideMatches } from "@/data/teams";
import { breadcrumbJsonLd, buildMetadata } from "@/lib/seo";

interface TeamPageProps {
  params: { teamSlug: string };
}

export function generateStaticParams() {
  return TEAM_GUIDES.map((team) => ({ teamSlug: team.slug }));
}

export function generateMetadata({ params }: TeamPageProps): Metadata {
  const guide = getTeamGuideBySlug(params.teamSlug);
  if (!guide) {
    return buildMetadata({
      title: "World Cup 2026 Team Guide Not Found",
      description: "World Cup 2026 team guide not found.",
      path: "/world-cup-2026",
    });
  }

  return buildMetadata({
    title: guide.title,
    description: guide.description,
    path: `/world-cup-2026/teams/${guide.slug}`,
    type: "article",
  });
}

export default function TeamGuidePage({ params }: TeamPageProps) {
  const guide = getTeamGuideBySlug(params.teamSlug);
  if (!guide) notFound();

  const matches = getTeamGuideMatches(guide);
  const path = `/world-cup-2026/teams/${guide.slug}`;

  return (
    <main className="content-page">
      <JsonLd
        data={breadcrumbJsonLd([
          { name: "Home", path: "/" },
          { name: "World Cup 2026", path: "/world-cup-2026" },
          { name: "Teams", path: "/world-cup-2026" },
          { name: guide.name, path },
        ])}
      />
      <div className="content-wrap">
        <StickyLiveScoresLink />
        <section className="wc-hero team-hero">
          <img src={`https://flagcdn.com/w40/${guide.flagCode}.png`} alt="" />
          <h1>{guide.title}</h1>
          <p>{guide.description}</p>
        </section>

        <section className="content-card">
          <div className="section-heading">
            <h2>What Travels</h2>
          </div>
          <div className="two-col-list">
            <div>
              <h3>Strengths</h3>
              <ul>
                {guide.strengths.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </div>
            <div>
              <h3>Questions</h3>
              <ul>
                {guide.questions.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        <MidArticleSignup />

        <section className="content-card">
          <div className="section-heading">
            <h2>{guide.name} Schedule</h2>
          </div>
          <div className="schedule-list">
            {matches.map((match) => (
              <a href={`/world-cup-2026/matches/${match.slug}`} className="schedule-list-row" key={match.slug}>
                <span>{match.dateShort} · {match.timeStr}</span>
                <strong>{match.home} vs {match.away}</strong>
                <em>{match.venueShort}</em>
              </a>
            ))}
          </div>
        </section>

        <section className="content-card">
          <div className="section-heading">
            <h2>Fantasy and Market Read</h2>
            <span className="ai-content-badge">Generated by AI</span>
          </div>
          <p>{guide.bettingAngle}</p>
          <div className="tag-row">
            {guide.fantasyTargets.map((player) => (
              <span key={player}>{player}</span>
            ))}
          </div>
          <FantasyToolCta />
        </section>

        <BottomArticleSignup />
      </div>
    </main>
  );
}
